"""Bring existing sites' CRM custom fields to the plain labels and help text.

The creating code only runs when a field is missing, so sites that already have
these rows keep the old text. Each row changes only while it still holds the old
value, so a site's own customisation is left alone and a rerun changes nothing.
"""

import frappe
from frappe.utils import cint

# (Custom Field name, property, old value, new value)
UPDATES = (
	("Assignment Rule-assign_condition_json", "hidden", 0, 1),
	("Assignment Rule-assign_condition_json", "description", "Autogenerated field by CRM App", ""),
	("Assignment Rule-unassign_condition_json", "hidden", 0, 1),
	("Assignment Rule-unassign_condition_json", "description", "Autogenerated field by CRM App", ""),
	("Email Template-reference_doctype", "label", "Doctype", "Document Type"),
	("WhatsApp Message-doco_provenance_section", "label", "Provenance", "System Details"),
	(
		"WhatsApp Message-doco_automation_source",
		"description",
		"e.g. taller.tracker_notify:Recibido",
		"Automation that sent this message.",
	),
	("CRM Deal-erpnext_customer", "label", "Customer in ERPNext", "Customer"),
	("CRM Product-erpnext_item_code", "label", "Item Code in ERPNext", "Item Code"),
	("Quotation-crm_deal", "label", "Frappe CRM Deal", "CRM Deal"),
	("Customer-crm_deal", "label", "Frappe CRM Deal", "CRM Deal"),
)


def execute():
	doctypes = set()
	for name, prop, old, new in UPDATES:
		current = frappe.db.get_value("Custom Field", name, prop)
		if current is None:
			continue
		if (cint(current) if prop == "hidden" else current) != old:
			continue
		frappe.db.set_value("Custom Field", name, prop, new, update_modified=False)
		doctypes.add(frappe.db.get_value("Custom Field", name, "dt"))
	for doctype in doctypes:
		frappe.clear_cache(doctype=doctype)
