"""Provenance for CRM's automatic owner assignments.

Setting a lead/deal owner (and Assignment Rules on them) creates a native ToDo.
That ToDo is ownership, not work: the record already lives in the sales
pipeline. Those rows are marked `crm_owner_assignment` when inserted so work
queues (Pendientes) can leave them out. A person's explicit «Asignar a» goes
through Frappe's assign_to without this context and stays an ordinary ToDo.
"""

from contextlib import contextmanager

import frappe
from frappe.custom.doctype.custom_field.custom_field import create_custom_fields
from frappe.utils import strip_html

FIELD = "crm_owner_assignment"
OWNER_FIELDS = {"CRM Lead": "lead_owner", "CRM Deal": "deal_owner"}


@contextmanager
def owner_assignment():
	previous = frappe.flags.crm_owner_assignment
	frappe.flags.crm_owner_assignment = True
	try:
		yield
	finally:
		frappe.flags.crm_owner_assignment = previous


def mark(doc, method=None):
	"""ToDo before_insert: owner path or Assignment Rule on a lead/deal."""
	if doc.reference_type not in OWNER_FIELDS or not doc.meta.has_field(FIELD):
		return
	if frappe.flags.crm_owner_assignment or doc.get("assignment_rule"):
		doc.set(FIELD, 1)


def ensure_field():
	if frappe.get_meta("ToDo").has_field(FIELD):
		return
	create_custom_fields(
		{
			"ToDo": [
				{
					"fieldname": FIELD,
					"fieldtype": "Check",
					"label": "CRM owner assignment",
					"description": "Autogenerated field by CRM App: set when CRM assigns a lead/deal to its owner",
					"insert_after": "assignment_rule",
					"read_only": 1,
					"hidden": 1,
					"no_copy": 1,
				}
			]
		}
	)
	frappe.clear_cache(doctype="ToDo")


def _default_descriptions(doctype, name, languages):
	return {frappe._("Assignment for {0} {1}", lang=lang).format(doctype, name) for lang in languages}


def backfill():
	"""Mark existing automatic owner assignments (rows created before the marker).

	Heuristic for legacy rows, documented in specs/pendientes-design.md:
	a ToDo on a CRM Lead/Deal is automatic when it came from an Assignment Rule,
	or when it is allocated to the record's current owner AND still carries
	Frappe's default text «Assignment for <DocType> <name>» (in English or a
	language in use on the site). Anything with a person's own description, or
	allocated to someone other than the owner, stays visible as real work.
	"""
	ensure_field()
	languages = {"en", frappe.db.get_default("lang") or "en"}
	languages.update(
		lang
		for lang in frappe.get_all("User", filters={"enabled": 1}, pluck="language", distinct=True)
		if lang
	)
	marked = 0
	for doctype, owner_field in OWNER_FIELDS.items():
		if not frappe.db.exists("DocType", doctype):
			continue
		rows = frappe.get_all(
			"ToDo",
			filters={"reference_type": doctype, FIELD: 0},
			fields=["name", "reference_name", "allocated_to", "description", "assignment_rule"],
		)
		owners = {}
		for row in rows:
			automatic = bool(row.assignment_rule)
			if not automatic and row.reference_name and row.allocated_to:
				if row.reference_name not in owners:
					owners[row.reference_name] = frappe.db.get_value(doctype, row.reference_name, owner_field)
				automatic = row.allocated_to == owners[row.reference_name] and strip_html(
					row.description or ""
				).strip() in _default_descriptions(doctype, row.reference_name, languages)
			if automatic:
				frappe.db.set_value("ToDo", row.name, FIELD, 1, update_modified=False)
				marked += 1
	return marked
